「バッチアプリ開発のノウハウ」をSpring Boot 3系にアップデート
Fintan-contents/spring-crib-notes pull request #33
Opened 2023-12-10 23:45 UTC by hiji

## 概要

## レビュー依頼前のチェックリスト

- [x] 作業時間を記録していること
- [x] セルフレビュー済みであること
- [x] PRに適切なtarget branchを設定済みであること

ソースコード特有の項目

- [x] 理解しづらいコードはコメントで補足説明済みであること
- [x] `./mvn clean verify`を実行して結果が`BUILD SUCCESS`であること

## 動作確認方法

- [x] READMEに沿って動作確認が可能であること

## レビューアに確認して欲しいポイント

- Spring Batch 5.x へのバージョンアップ
- `JsrJobParametersConverter`が削除されたので流用
- `JobBuilderFactory`、`stepBuilderFactory`からの移行
- `ItemWriter`インタフェース変更に対応
- `EnableBatchProcessing`アノテーションの除去
- テストで`JobLauncherTestUtils`が動作しなくなったため対応
- READMEに誤り（doma2のログは出力されない）があったため修正

## レビューアへの申し送り事項

(もしあれば書く)

## その他、気になること

(もしあれば書く)

---

## レビュー後、マージ前のチェックリスト（レビューア用のチェックリスト）

- [ ] レビュー時間を記録していること
- [ ] PRに適切なtarget branchを設定済みであること

---

| 作業分類             |時間(h)|
|------------------|---|
| 実装・執筆            |2|
| レビュー(backpaper0) |0|

2023-12-12 00:52 UTC, tisurgm requested changes

2023-12-12 00:52 UTC, tisurgm commented on doc/batch/run-application/index.rst
スタックトレースにSpring Boot 2.7.5.jarが出てきているので、できれば3.2.xにしたいですね。

2023-12-12 00:56 UTC, tisurgm commented on doc/batch/run-application/index.rst
`spring.batch.job.names`は廃止され、
`spring.batch.job.name`に変更されました。
それに伴い複数ジョブを指定することもできなくなりました。

2023-12-13 01:15 UTC, hiji commented
上記2点のコメントから、バッチ実行方法のページを全面的に見直しました。検証用のサンプルが無く、前回検証方法がわからない状態になってしまったため、検証用のサンプルプロジェクトも追加しました。

2023-12-13 05:03 UTC, tisurgm approved these changes

2023-12-13 05:03 UTC, merged