「Webアプリ開発のノウハウ - セッション管理」をSpring Boot 3系にアップデート
Fintan-contents/spring-crib-notes pull request #34
Opened 2023-12-11 01:00 UTC by hiji

## 概要

## レビュー依頼前のチェックリスト

- [x] 作業時間を記録していること
- [x] セルフレビュー済みであること
- [x] PRに適切なtarget branchを設定済みであること

ソースコード特有の項目

- [ ] 理解しづらいコードはコメントで補足説明済みであること
- [ ] `./mvn clean verify`を実行して結果が`BUILD SUCCESS`であること

## 動作確認方法

- ドキュメント修正のみのため無し

## レビューアに確認して欲しいポイント

- Spring SessionのRedis接続を開発環境でのみ無効にする方法

## レビューアへの申し送り事項

- ドキュメントのリンク先は別途まとめて見直します

## その他、気になること

(もしあれば書く)

---

## レビュー後、マージ前のチェックリスト（レビューア用のチェックリスト）

- [ ] レビュー時間を記録していること
- [ ] PRに適切なtarget branchを設定済みであること

---

| 作業分類             |時間(h)|
|------------------|---|
| 実装・執筆            |1|
| レビュー(backpaper0) |0.1|

2023-12-11 12:11 UTC, tisurgm requested changes

2023-12-11 12:11 UTC, tisurgm commented on doc/web/session/session-redis.rst
> +  （ 選択順は :spring-framework-doc:`Spring Session <reference/html/web.html#spring-web>` を参照してください）
参考ドキュメントが間違っていると思います。

2023-12-12 03:28 UTC, hiji commented on doc/web/session/session-redis.rst
> +  （ 選択順は :spring-framework-doc:`Spring Session <reference/html/web.html#spring-web>` を参照してください）
修正しました。

f961524758ccf3c1f04d860529997e237ac46f8e

2023-12-12 05:51 UTC, tisurgm commented on doc/web/session/session-redis.rst
> +  （ 選択順は :spring-framework-doc:`Spring Session <reference/html/web.html#spring-web>` を参照してください）
`:spring-framework-doc:`ってなってるけど、これSpring Sessionじゃなくて https://docs.spring.io/spring-framework/reference/web.html へのリンクになるんじゃないですか？

2023-12-12 05:54 UTC, hiji commented on doc/web/session/session-redis.rst
> +  （ 選択順は :spring-framework-doc:`Spring Session <reference/html/web.html#spring-web>` を参照してください）
AutoConfgureの話なので、SpringBootの以下ドキュメントにある順序の話が該当するとおもってそのリンクにしていました。内容的には妥当とは思ったのですが、どうでしょうか？

https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.spring-session

2023-12-12 08:40 UTC, tisurgm commented on doc/web/session/session-redis.rst
> +  （ 選択順は :spring-framework-doc:`Spring Session <reference/html/web.html#spring-web>` を参照してください）
`:spring-framework-doc:`じゃなくて`:spring-boot-doc:`じゃないですか？

2023-12-12 13:08 UTC, hiji commented on doc/web/session/session-redis.rst
> +  （ 選択順は :spring-framework-doc:`Spring Session <reference/html/web.html#spring-web>` を参照してください）
すみません、仰る通りで間違っていました。
~~ただ他にもリンク修正が必要な個所が多いことがわかり、実際に生成してリンクを確認することも考えて、ドキュメント全体のリンク先変更と合わせて対応とさせてください。~~

修正しました。

a66b99345c5bf3159da7a85bb1279a24dad3df3f

2023-12-13 00:15 UTC, tisurgm approved these changes

2023-12-13 00:15 UTC, merged