「SpringからAWSマネージドサービスを利用する際のノウハウ」をSpring Boot 3系にアップデート
Fintan-contents/spring-crib-notes pull request #37
Opened 2023-12-12 07:25 UTC by hiji

## 概要

## レビュー依頼前のチェックリスト

- [x] 作業時間を記録していること
- [x] セルフレビュー済みであること
- [x] PRに適切なtarget branchを設定済みであること

ソースコード特有の項目

- [x] 理解しづらいコードはコメントで補足説明済みであること
- [x] `./mvn clean verify`を実行して結果が`BUILD SUCCESS`であること

## 動作確認方法

- [x] READMEに沿って動作確認できること

## レビューアに確認して欲しいポイント

- Spring Cloud AWS を 3.1.0 へバージョンアップ
  - テスト用の[LocalStack Java Utils](https://github.com/localstack/localstack-java-utils)が[TestContainer](https://java.testcontainers.org/modules/localstack/)へ移行を促していたため、移行
  - RDS(JDBC)機能が 3.x から削除されていたため、サンプルを削除してドキュメントを見直し
- テスト方法の変更によりサンプルでプロファイルを使用しなくてもよくなったため、プロファイルを統一

## レビューアへの申し送り事項

(もしあれば書く)

## その他、気になること

(もしあれば書く)

---

## レビュー後、マージ前のチェックリスト（レビューア用のチェックリスト）

- [ ] レビュー時間を記録していること
- [ ] PRに適切なtarget branchを設定済みであること

---

| 作業分類             |時間(h)|
|------------------|---|
| 実装・執筆            |0|
| レビュー(backpaper0) |0|

2023-12-13 12:32 UTC, tisurgm requested changes

2023-12-13 12:32 UTC, tisurgm commented on doc/aws/s3/index.rst
`application-local.properties`は削除されたので`literalinclude`のパスを変更してください。

2023-12-13 12:32 UTC, tisurgm commented on doc/aws/ses/index.rst
`application-local.properties`は削除されたので`literalinclude`のパスを変更してください。

2023-12-13 12:32 UTC, tisurgm commented on samples/aws/s3/src/main/java/keel/aws/s3/AwsS3UploadService.java
> +            s3Template.upload(properties.getBucketName(), path.getFileName().toString(), Files.newInputStream(path));
`Files.newInputStream(path)`から返される`InputStream`はtry-with-resourcesで確実にクローズした方が良いと思います。

2023-12-13 12:46 UTC, hiji commented on doc/aws/s3/index.rst
対応しました。

bfa1ca49226abe8dcd356db9636491677c650219

2023-12-13 12:46 UTC, hiji commented on doc/aws/ses/index.rst
対応しました。

fb241e29cd0e2d8462146066bf384a576701eda7

2023-12-13 12:46 UTC, hiji commented on samples/aws/s3/src/main/java/keel/aws/s3/AwsS3UploadService.java
> +            s3Template.upload(properties.getBucketName(), path.getFileName().toString(), Files.newInputStream(path));
対応しました。

bb33b1143904ec8561be8a4953b02baf6457b3db

2023-12-14 00:11 UTC, tisurgm approved these changes

2023-12-14 00:11 UTC, merged