Logbookを使用したリクエストレスポンスログ出力のノウハウを追加
Fintan-contents/spring-crib-notes pull request #39
Opened 2023-12-14 09:50 UTC by hiji

## 概要

## レビュー依頼前のチェックリスト

- [x] 作業時間を記録していること
- [x] セルフレビュー済みであること
- [x] PRに適切なtarget branchを設定済みであること

ソースコード特有の項目

- [x] 理解しづらいコードはコメントで補足説明済みであること
- [x] `./mvn clean verify`を実行して結果が`BUILD SUCCESS`であること

## 動作確認方法

- [ ] ...
- [ ] ...

## レビューアに確認して欲しいポイント

- Logbookを使用するためのガイド
- Logbookを使用したサンプルプロジェクト

## レビューアへの申し送り事項

(もしあれば書く)

## その他、気になること

(もしあれば書く)

---

## レビュー後、マージ前のチェックリスト（レビューア用のチェックリスト）

- [ ] レビュー時間を記録していること
- [ ] PRに適切なtarget branchを設定済みであること

---

| 作業分類             |時間(h)|
|------------------|---|
| 実装・執筆            |5|
| レビュー(backpaper0) |0|

2023-12-15 10:57 UTC, tisurgm requested changes

2023-12-15 10:57 UTC, tisurgm commented on samples/common/api-logging/src/main/java/keel/apilogging/ApiLoggingApp.java
> +import org.zalando.logbook.BodyFilter;
不要な`import`です。

2023-12-15 10:57 UTC, tisurgm commented on samples/common/api-logging/src/main/java/keel/apilogging/ApiLoggingApp.java
> +import org.zalando.logbook.core.BodyFilters;
不要な`import`です。

2023-12-15 10:57 UTC, tisurgm commented on samples/common/api-logging/src/test/java/keel/apilogging/ApiLoggingControllerTest.java
> +        Map<String, String> response = restTemplate.getForObject("http://localhost:" + port + "/users", Map.class);
左辺は総称型、右辺はraw型なので警告が出ますね。
`var`を使うか、`Map`をやめて`keel.apilogging.User`を使うか、どちらかが良いと思います。

2023-12-15 10:57 UTC, tisurgm commented on samples/common/api-logging/src/test/java/keel/apilogging/ApiLoggingControllerTest.java
> +                Map.of("id", "456", "username", "fuga"), Map.class);
左辺は総称型、右辺はraw型なので警告が出ますね。
`var`を使うか、`Map`をやめて`keel.apilogging.User`を使うか、どちらかが良いと思います。

2023-12-15 10:57 UTC, tisurgm commented on samples/common/api-logging/pom.xml
> +      <version>5.15.0</version>
`parent`でバージョン管理した方が良いと思いました。

2023-12-15 10:57 UTC, tisurgm commented on samples/common/api-logging/src/main/java/keel/apilogging/ApiLoggingController.java
> +    @GetMapping("/users")
1件の`User`しか返さないので`/user`で良いと思いました。

2023-12-15 10:57 UTC, tisurgm commented on samples/common/api-logging/src/main/java/keel/apilogging/ApiLoggingController.java
> +    @PostMapping("/users")
1件の`User`しか返さないので`/user`で良いと思いました。

2023-12-15 10:57 UTC, tisurgm commented on doc/common/log/web-api-log.rst
> +  * リクエスト送信にはRestTemplateを使用し、メッセージの形式にはJSONを使用する
描画されたHTMLを見るとネストした箇条書きになっていません。
前後に空行が必要では？

2023-12-15 10:57 UTC, tisurgm commented on doc/common/log/web-api-log.rst
> +* 実装したAPIへのリクエストを受信したら、リクエストおよびレスポンスのログを出力する。
箇条書きの末尾は句点なしでお願いします。

2023-12-15 10:57 UTC, tisurgm commented on doc/common/log/web-api-log.rst
> +* 外部のAPIへリクエストを送信したら、リクエストおよびレスポンスのログを出力する。
箇条書きの末尾は句点なしでお願いします。

2023-12-15 12:36 UTC, hiji commented on doc/common/log/web-api-log.rst
> +  * リクエスト送信にはRestTemplateを使用し、メッセージの形式にはJSONを使用する
対応しました

447d6b2efba855c00ba800f0130e5fc3fc784c67

2023-12-15 12:37 UTC, hiji commented on doc/common/log/web-api-log.rst
> +* 外部のAPIへリクエストを送信したら、リクエストおよびレスポンスのログを出力する。
修正しました。

ccccc0f810777e08986425d353f8e4ae5f6cc2d9

2023-12-15 12:37 UTC, hiji commented on doc/common/log/web-api-log.rst
> +* 実装したAPIへのリクエストを受信したら、リクエストおよびレスポンスのログを出力する。
修正しました。

ccccc0f810777e08986425d353f8e4ae5f6cc2d9

2023-12-15 12:59 UTC, hiji commented on samples/common/api-logging/pom.xml
> +      <version>5.15.0</version>
修正しました。

842068bf848f2567de183ab3b90b417217b41e2e

2023-12-15 12:59 UTC, hiji commented on samples/common/api-logging/src/main/java/keel/apilogging/ApiLoggingApp.java
> +import org.zalando.logbook.BodyFilter;
削除しました。

d9ab4800de6dded6f58b956fc5fa2a7dfbdda485

2023-12-15 13:00 UTC, hiji commented on samples/common/api-logging/src/main/java/keel/apilogging/ApiLoggingApp.java
> +import org.zalando.logbook.core.BodyFilters;
削除しました。

d9ab4800de6dded6f58b956fc5fa2a7dfbdda485

2023-12-15 13:00 UTC, hiji commented on samples/common/api-logging/src/main/java/keel/apilogging/ApiLoggingController.java
> +    @GetMapping("/users")
見直しました。

5fd17df78de59713cbf9eece9e6d2e0f13e6c0fa

2023-12-15 13:04 UTC, hiji commented on samples/common/api-logging/src/test/java/keel/apilogging/ApiLoggingControllerTest.java
> +        Map<String, String> response = restTemplate.getForObject("http://localhost:" + port + "/users", Map.class);
修正しました。

5fd17df78de59713cbf9eece9e6d2e0f13e6c0fa

2023-12-15 13:05 UTC, hiji commented on samples/common/api-logging/src/test/java/keel/apilogging/ApiLoggingControllerTest.java
> +                Map.of("id", "456", "username", "fuga"), Map.class);
周辺含めて見直しました。

5fd17df78de59713cbf9eece9e6d2e0f13e6c0fa
1331d2ec1b97026f9d9b04f843d0c4c9c6377bb7 （修正後に再修正）

2023-12-16 21:27 UTC, tisurgm approved these changes

2023-12-16 21:28 UTC, merged